### ISSUE TITLE
Meta Tag 无法在Next.js page中使用

### ISSUE THREAD

**Issue by forwells** [nalabdou/html-meta-tags-hero#1]
vscode无法在js文件中进行自动提示

**Comment by nalabdou** [comment]
@forwells JS files Support will be added next update.

**Comment by nalabdou** [comment]
JavaScript files support added

**Comment by doggy8088** [comment]
@nalabdou Did you update your extension on vscode marketplace?

**Comment by nalabdou** [comment]
> @nalabdou Did you update your extension on vscode marketplace?

@doggy8088 Yes i did, just now :), sorry about this now you can use it inside any .js/jsx file. 
Best regards
