### ISSUE TITLE
After installing successfully in VS Code, it failed to run.

### ISSUE THREAD

**Issue by cd10anil** [nalabdou/html-meta-tags-hero#2]
It is not giving any snippets , and when looked into runtime status tab, it says 'Unknown language in `contributes.html-meta-tags-hero.language`. Provided value: twig" The VS code is updated with below details: 
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by cd10anil** [comment]
I have installed another extension "Twig code snippets" from author after which runtime status dont show any error but this snippet still not working (yes, restarted the vs code)

**Comment by nalabdou** [comment]
@cd10anil Will check about that
